CXX = g++-14
CXXFLAGS = -fopenmp

00_hello: 00_hello.cpp
	$(CXX) $(CXXFLAGS) 00_hello.cpp
01_num_threads: 01_num_threads.cpp
	$(CXX) $(CXXFLAGS) 01_num_threads.cpp
02_loop: 02_loop.cpp
	$(CXX) $(CXXFLAGS) 02_loop.cpp
03_iterator: 03_iterator.cpp
	$(CXX) $(CXXFLAGS) 03_iterator.cpp
04_scope: 04_scope.cpp
	$(CXX) $(CXXFLAGS) 04_scope.cpp
05_scope: 05_scope.cpp 05_bar.cpp
	$(CXX) $(CXXFLAGS) 05_scope.cpp 05_bar.cpp
06_sections: 06_sections.cpp
	$(CXX) $(CXXFLAGS) 06_sections.cpp
07_private: 07_private.cpp
	$(CXX) $(CXXFLAGS) 07_private.cpp
08_tasks: 08_tasks.cpp
	$(CXX) $(CXXFLAGS) 08_tasks.cpp
09_reduction: 09_reduction.cpp
	$(CXX) $(CXXFLAGS) 09_reduction.cpp
10_atomic: 10_atomic.cpp
	$(CXX) $(CXXFLAGS) 10_atomic.cpp
11_scan: 11_scan.cpp
	$(CXX) $(CXXFLAGS) 11_scan.cpp
12_pi: 12_pi.cpp
	$(CXX) $(CXXFLAGS) 12_pi.cpp
13_merge_sort: 13_merge_sort.cpp
	$(CXX) $(CXXFLAGS) 13_merge_sort.cpp
14_bucket_sort: 14_bucket_sort.cpp
	$(CXX) $(CXXFLAGS) 14_bucket_sort.cpp
